
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ywycxnskqrtdivywngsh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3eWN4bnNrcXJ0ZGl2eXduZ3NoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNDU4OTgsImV4cCI6MjA2MDYyMTg5OH0.jr7iFM61vjdsZg1K6Ul2lwJa3NcdrYXQm8RedSJnhvE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
